<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJRNYbEp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJRNYbEp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJRNYbEp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJRNYbEp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJRNYbEp\App_KernelDevDebugContainer([
    'container.build_hash' => 'JRNYbEp',
    'container.build_id' => 'eed860e9',
    'container.build_time' => 1622910658,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJRNYbEp');
